<a href="https://colab.research.google.com/github/rhkralstj/DCOM_ML/blob/main/Week1/Answer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# 셀 1: 라이브러리 임포트
import numpy as np
import pandas as pd

In [4]:
# ==========================================
# [문제 1 정답] 공공 CSV 데이터를 활용한 ML 전처리
# ==========================================
csv_url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'

# 1-1. CSV 파일 불러오기
df = pd.read_csv(csv_url)

# 1-2. 결측치 확인 및 처리
# inplace=True를 사용하거나, 해당 컬럼 자체에 다시 할당하여 원본을 수정합니다.
df['Age'] = df['Age'].fillna(df['Age'].mean())

# 1-3. 데이터 필터링
# 두 개 이상의 조건을 결합할 때는 반드시 각 조건을 괄호로 묶고 비트 연산자(&)를 사용해야 합니다.
df_filtered = df[(df['Pclass'] == 1) & (df['Age'] >= 30)]

# 1-4. 그룹화 및 집계
mean_fare_by_survived = df_filtered.groupby('Survived')['Fare'].mean()

# [결과 확인]
print("--- [문제 1 결과] ---")
print(mean_fare_by_survived)

--- [문제 1 결과] ---
Survived
0    52.113832
1    97.058800
Name: Fare, dtype: float64


In [5]:
# ==========================================
# [문제 2 정답] 모델 성능 향상을 위한 데이터 스케일링
# ==========================================
np.random.seed(42)
X_features = np.random.randint(10, 1000, size=(5, 3)).astype(float)

# 2-1. 각 열(특성, axis=0)별 평균 계산
mean_vals = np.mean(X_features, axis=0)
# 다른 방법: mean_vals = X_features.mean(axis=0)

# 2-2. 각 열(특성, axis=0)별 표준편차 계산
std_vals = np.std(X_features, axis=0)
# 다른 방법: std_vals = X_features.std(axis=0)

# 2-3. 표준화된 데이터 연산 (브로드캐스팅)
X_scaled = (X_features - mean_vals) / std_vals

# [결과 확인]
print("\n--- [문제 2 결과] ---")
print("표준화 후 데이터:\n", X_scaled)
print("\n열별 평균 확인 (0에 수렴):", np.round(np.mean(X_scaled, axis=0), 4))
print("열별 표준편차 확인 (1에 수렴):", np.std(X_scaled, axis=0))


--- [문제 2 결과] ---
표준화 후 데이터:
 [[-0.93864885  0.71408525  1.56229883]
 [-0.16030232 -0.98833538 -0.94922068]
 [ 1.83189416 -1.43334503  0.77923951]
 [-0.85062157  0.87449571 -0.49402767]
 [ 0.11767858  0.83309946 -0.89828999]]

열별 평균 확인 (0에 수렴): [-0.  0.  0.]
열별 표준편차 확인 (1에 수렴): [1. 1. 1.]


In [6]:
# ==========================================
# [문제 3 정답] 회귀 모델 평가 지표 직접 구현하기
# ==========================================
y_true = np.array([3.0, -0.5, 2.0, 7.0])
y_pred = np.array([2.5, 0.0, 2.1, 7.8])

# 3-1. 오차(실제값 - 예측값)의 제곱
squared_errors = (y_true - y_pred) ** 2

# 3-2. 평균 제곱 오차(MSE) 계산
mse = np.mean(squared_errors)
# 다른 방법: mse = squared_errors.mean()

# 한 줄로 요약 구현
mse_one_line = np.mean((y_true - y_pred) ** 2)

# [결과 확인]
print("\n--- [문제 3 결과] ---")
print(f"MSE: {mse}")
print(f"한 줄 구현 MSE: {mse_one_line}")


--- [문제 3 결과] ---
MSE: 0.2874999999999999
한 줄 구현 MSE: 0.2874999999999999
